import { findPortMethodParam } from './validateProfile';

export function formatCommand(adapter, port, method, param) {
    if (adapter.model === 'iTachIP2CC') {
        return { address: adapter.ip, command: `Relay ${param.position} ${param.name}` };
    }
    let command = method.command;
    if (method.type === 'actions' && param) {
        command = command.replace('%', param.value);
    }
    return { address: adapter.ip, command };
}

function findAdapterForPort(json, portId) {
    return json.adapters.find((a) => (a.ports || []).some((p) => p.id === portId));
}

function applyITachIP2CCMethods(json) {
    json.adapters
        .filter((adapter) => adapter.model === 'iTachIP2CC')
        .forEach((adapter) => {
            adapter.ports.forEach((port) => {
                port.methods = [
                    {
                        name: 'Power',
                        id: 'power',
                        params: [
                            { name: 'On', id: 'on', position: port.position },
                            { name: 'Off', id: 'off', position: port.position },
                        ],
                    },
                ];

                // The autogenerated method gets the same main_method treatment as
                // any other primary control, so we add the style and let it flow
                // through the normal style-inlining pass below.
                if (!Array.isArray(json.styles)) json.styles = [];
                json.styles.push(port.id + '.main_method=power');
            });
        });
}

function applyStyles(json) {
    if (!Array.isArray(json.styles) || json.styles.length === 0) return;

    const styleRegex =
        /^(?<port>[^.=]*)\.?(?<method>[^.=]*)\.?(?<param>[^.=]*)\.(?<style>[^.=]*)=(?<value>.*)$/;

    json.styles.forEach((style) => {
        if (style.includes('..')) return;
        const result = styleRegex.exec(style);
        if (!result) return;

        let port = null;
        for (const adapter of json.adapters) {
            const found = (adapter.ports || []).find((p) => p.id === result.groups.port);
            if (found) {
                port = found;
                break;
            }
        }
        if (!port) return;

        switch (result.groups.style) {
            case 'icon': {
                const icon = result.groups.value;
                if (result.groups.method) {
                    const method = port.methods.find((m) => m.id === result.groups.method);
                    if (!method) return;
                    if (result.groups.param) {
                        const param = (method.params || []).find(
                            (p) => p.id === result.groups.param
                        );
                        if (param) param.icon = icon;
                    } else {
                        method.icon = icon;
                    }
                } else {
                    port.icon = icon;
                }
                break;
            }
            case 'main_method': {
                port.main_method = port.methods.find(
                    (m) => m.id === result.groups.value
                );
                break;
            }
            case 'invisible': {
                if (!result.groups.param) {
                    const method = port.methods.find(
                        (m) => m.id === result.groups.method
                    );
                    if (method) {
                        const hidden = result.groups.value === 'true';
                        method.visible = !hidden;
                        // Track the user's explicit intent separately from the
                        // visible flag, which also gets flipped to false for
                        // methods that are rolled up into the port header.
                        // The renderer keys off userHidden to decide whether
                        // to actually hide content (which Zoom does for the
                        // main_method when it is also marked invisible).
                        method.userHidden = hidden;
                    }
                }
                break;
            }
        }
    });
}

function applyVisibility(json) {
    json.adapters.forEach((adapter) => {
        adapter.ports.forEach((port) => {
            port.showOnlyMainMethod = Boolean(port.main_method && port.methods.length === 1);

            port.methods.forEach((method) => {
                // `rolledUp` means the method is the port's main_method and
                // already appears in the port header — it should never render
                // as a row in the methods list, even when "Show hidden
                // controls" is on. `visible: false` from this branch is just a
                // courtesy fallback; the renderer keys off `rolledUp` directly.
                method.rolledUp = Boolean(
                    port.main_method && method.id === port.main_method.id
                );
                if (method.rolledUp) {
                    method.visible = false;
                }
                if (method.visible !== false) {
                    method.visible = true;
                }
            });
        });
    });
}

function resolveCommandRefs(json, commandRefs) {
    return commandRefs.map((commandRef) => {
        const { port, method, param } = findPortMethodParam(json, commandRef);
        const adapter = findAdapterForPort(json, port.id);
        return formatCommand(adapter, port, method, param);
    });
}

function resolveScenes(json) {
    if (!Array.isArray(json.scenes)) return;

    json.scenes.forEach((scene) => {
        scene.resolvedCommands = resolveCommandRefs(json, scene.commands);
    });
}

function resolveRules(json) {
    // Flatten the rules object into an ordered array so the UI can iterate it
    // without having to filter $comment and re-resolve on every render. Empty
    // rules (handler defined but no commands) are kept so the user can see
    // they've claimed the event even if it currently does nothing.
    if (!json.rules || typeof json.rules !== 'object') {
        json.resolvedRules = [];
        return;
    }

    json.resolvedRules = Object.entries(json.rules)
        .filter(([event, commands]) => event !== '$comment' && Array.isArray(commands))
        .map(([event, commands]) => ({
            event,
            commands: resolveCommandRefs(json, commands),
        }));
}

function detectEventOnly(json) {
    // `zr_event_only=true` is a special token in the `styles` array (not a
    // dot-notation style) that tells Zoom Rooms to suppress the entire Native
    // Room Controls UI. We expose it on the transformed profile so the preview
    // can render an explanatory placeholder instead of blank space.
    json.eventOnly =
        Array.isArray(json.styles) && json.styles.includes('zr_event_only=true');
}

export function transformProfile(json) {
    applyITachIP2CCMethods(json);
    applyStyles(json);
    applyVisibility(json);
    detectEventOnly(json);
    resolveScenes(json);
    resolveRules(json);
    return json;
}
