import { findPortMethodParam } from './validateProfile';

export function formatCommand(adapter, port, method, param) {
    const address = adapter && adapter.ip ? adapter.ip : adapter && adapter.com ? adapter.com : '';
    if (adapter && adapter.model === 'iTachIP2CC') {
        return {
            address,
            command: `Relay ${param ? param.position : ''} ${param ? param.name : ''}`,
        };
    }
    let command = method && typeof method.command === 'string' ? method.command : '';
    if (method && method.type === 'actions' && param) {
        command = command.replace('%', param.value);
    }
    return { address, command };
}

function findAdapterForPort(json, portId) {
    if (!Array.isArray(json.adapters)) return null;
    return (
        json.adapters.find((a) =>
            Array.isArray(a && a.ports) ? a.ports.some((p) => p && p.id === portId) : false
        ) || null
    );
}

function applyITachIP2CCMethods(json) {
    if (!Array.isArray(json.adapters)) return;
    json.adapters
        .filter((adapter) => adapter && adapter.model === 'iTachIP2CC')
        .forEach((adapter) => {
            if (!Array.isArray(adapter.ports)) return;
            adapter.ports.forEach((port) => {
                if (!port) return;
                port.methods = [
                    {
                        name: 'Power',
                        id: 'power',
                        params: [
                            { name: 'On', id: 'on', position: port.position },
                            { name: 'Off', id: 'off', position: port.position },
                        ],
                    },
                ];

                // The autogenerated method gets the same main_method treatment as
                // any other primary control, so we add the style and let it flow
                // through the normal style-inlining pass below.
                if (!Array.isArray(json.styles)) json.styles = [];
                if (port.id) json.styles.push(port.id + '.main_method=power');
            });
        });
}

function applyStyles(json) {
    if (!Array.isArray(json.styles) || json.styles.length === 0) return;
    if (!Array.isArray(json.adapters)) return;

    const styleRegex =
        /^(?<port>[^.=]*)\.?(?<method>[^.=]*)\.?(?<param>[^.=]*)\.(?<style>[^.=]*)=(?<value>.*)$/;

    json.styles.forEach((style) => {
        if (typeof style !== 'string' || style.includes('..')) return;
        const result = styleRegex.exec(style);
        if (!result) return;

        let port = null;
        for (const adapter of json.adapters) {
            if (!adapter || !Array.isArray(adapter.ports)) continue;
            const found = adapter.ports.find((p) => p && p.id === result.groups.port);
            if (found) {
                port = found;
                break;
            }
        }
        if (!port) return;

        switch (result.groups.style) {
            case 'icon': {
                const icon = result.groups.value;
                if (result.groups.method) {
                    const method = Array.isArray(port.methods)
                        ? port.methods.find((m) => m && m.id === result.groups.method)
                        : null;
                    if (!method) return;
                    if (result.groups.param) {
                        const param = Array.isArray(method.params)
                            ? method.params.find((p) => p && p.id === result.groups.param)
                            : null;
                        if (param) param.icon = icon;
                    } else {
                        method.icon = icon;
                    }
                } else {
                    port.icon = icon;
                }
                break;
            }
            case 'main_method': {
                if (Array.isArray(port.methods)) {
                    port.main_method = port.methods.find(
                        (m) => m && m.id === result.groups.value
                    );
                }
                break;
            }
            case 'invisible': {
                if (!result.groups.param) {
                    const method = Array.isArray(port.methods)
                        ? port.methods.find((m) => m && m.id === result.groups.method)
                        : null;
                    if (method) {
                        const hidden = result.groups.value === 'true';
                        method.visible = !hidden;
                        // Track the user's explicit intent separately from the
                        // visible flag, which also gets flipped to false for
                        // methods that are rolled up into the port header.
                        // The renderer keys off userHidden to decide whether
                        // to actually hide content (which Zoom does for the
                        // main_method when it is also marked invisible).
                        method.userHidden = hidden;
                    }
                }
                break;
            }
        }
    });
}

function applyVisibility(json) {
    if (!Array.isArray(json.adapters)) return;
    json.adapters.forEach((adapter) => {
        if (!adapter || !Array.isArray(adapter.ports)) return;
        adapter.ports.forEach((port) => {
            if (!port) return;
            const methods = Array.isArray(port.methods) ? port.methods : [];
            port.showOnlyMainMethod = Boolean(port.main_method && methods.length === 1);

            methods.forEach((method) => {
                if (!method) return;
                // `rolledUp` means the method is the port's main_method and
                // already appears in the port header — it should never render
                // as a row in the methods list, even when "Show hidden
                // controls" is on. `visible: false` from this branch is just a
                // courtesy fallback; the renderer keys off `rolledUp` directly.
                method.rolledUp = Boolean(
                    port.main_method && method.id === port.main_method.id
                );
                if (method.rolledUp) {
                    method.visible = false;
                }
                if (method.visible !== false) {
                    method.visible = true;
                }
            });
        });
    });
}

export function resolveCommandRefs(json, commandRefs) {
    // Returns one entry per ref so the Output pane / Log can show the
    // mapping from `port.method[.param]` → `address: command-bytes`. Refs we
    // can't resolve are kept as `{ ref, error }` so the user can see what
    // failed instead of silently dropping it — the rest of the list still
    // resolves and renders.
    if (!Array.isArray(commandRefs)) return [];
    const out = [];
    for (const ref of commandRefs) {
        if (typeof ref !== 'string') {
            out.push({ ref: String(ref), error: 'not a string' });
            continue;
        }
        const r = findPortMethodParam(json, ref);
        if (r.error) {
            out.push({ ref, error: r.error });
            continue;
        }
        if (!r.port) {
            out.push({ ref, error: 'no matching port' });
            continue;
        }
        const adapter = findAdapterForPort(json, r.port.id);
        if (!adapter) {
            out.push({ ref, error: 'no adapter owns this port' });
            continue;
        }
        const fc = formatCommand(adapter, r.port, r.method, r.param);
        out.push({ ref, address: fc.address, command: fc.command });
    }
    return out;
}

function resolveScenes(json) {
    if (!Array.isArray(json.scenes)) return;

    json.scenes.forEach((scene) => {
        scene.resolvedCommands = resolveCommandRefs(json, scene.commands);
    });
}

function resolveRules(json) {
    // Flatten the rules object into an ordered array so the UI can iterate it
    // without having to filter $comment and re-resolve on every render. Empty
    // rules (handler defined but no commands) are kept so the user can see
    // they've claimed the event even if it currently does nothing.
    if (!json.rules || typeof json.rules !== 'object') {
        json.resolvedRules = [];
        return;
    }

    json.resolvedRules = Object.entries(json.rules)
        .filter(([event, commands]) => event !== '$comment' && Array.isArray(commands))
        .map(([event, commands]) => ({
            event,
            commands: resolveCommandRefs(json, commands),
        }));
}

function detectEventOnly(json) {
    // `zr_event_only=true` is a special token in the `styles` array (not a
    // dot-notation style) that tells Zoom Rooms to suppress the entire Native
    // Room Controls UI. We expose it on the transformed profile so the preview
    // can render an explanatory placeholder instead of blank space.
    json.eventOnly =
        Array.isArray(json.styles) && json.styles.includes('zr_event_only=true');
}

export function transformProfile(json) {
    applyITachIP2CCMethods(json);
    applyStyles(json);
    applyVisibility(json);
    detectEventOnly(json);
    resolveScenes(json);
    resolveRules(json);
    return json;
}
